### ISSUE TITLE
#<NameError: undefined local variable or method `base' for nil:NilClass>

### ISSUE THREAD

**Issue by Aqualon** [teamcapybara/capybara#1846]
## Meta
Capybara Version:
2.12.1
Driver Information (and browser if relevant):
selenium-webdriver 3.3.0

## Expected Behavior
Test should not fail with exception #<NameError: undefined local variable or method `base' for nil:NilClass>

## Actual Behavior
Testcase fails with #<NameError: undefined local variable or method `base' for nil:NilClass>

## Steps to reproduce
Since update from capybara 2.11.0 to 2.12.1 we have failing tests. We do a find with a selector and fail with the NameError. The code in https://github.com/teamcapybara/capybara/blame/master/lib/capybara/session.rb#L785 contains `[nil, :frame].include? scope`. The `scope` variable in our case is `#<Capybara::Node::Element tag="article" path="/html/body/div[1]/main/div[2]/div/div/div/div[2]/div[1]/div/div/section/article[3]">`. The `include?` check subsequently hits https://github.com/teamcapybara/capybara/blob/master/lib/capybara/node/matchers.rb#L677 where `self` is the `nil`-value passed on from the code in `session.rb`. Since `nil` does not have a `base` method, we see the error.

This issue only seems to happen in test cases, where we use within.

## Stacktrace
```
capybara-2.12.1/lib/capybara/node/matchers.rb:680:in `rescue in =='
capybara-2.12.1/lib/capybara/node/matchers.rb:677:in `=='
capybara-2.12.1/lib/capybara/session.rb:796:in `include?'
capybara-2.12.1/lib/capybara/session.rb:796:in `current_scope'
capybara-2.12.1/lib/capybara/session.rb:780:in `block (2 levels) in <class:Session>'
capybara-2.12.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
<our spec calling find>
```

**Comment by twalpole** [comment]
Please show an example of a test that causes this

**Comment by Aqualon** [comment]
If found this minimal testcase breaking with capybara 2.12.1 and working with 2.11.0

```
require 'rspec'
require 'capybara/rspec'

include Capybara::Node::Matchers

feature 'Error', js: true do
  scenario 'check bar' do
    visit 'http://output.jsbin.com/cucixureve/2'
    articles = all('.article')
    within(articles[1]) do
      bar = find('.bar')
      expect(bar).to have_content('bar')
    end
  end
end
```

If I remove the `include Capybara::Node::Matchers`, the test works. With it I get the error

```
  1) Error check bar
     Failure/Error: bar = find('.bar')
     
     NameError:
       undefined local variable or method `base' for nil:NilClass
```

The include happens in an internal gem used to set up integration tests across teams in my company, so I don't know exactly what was the use case behind adding it.

But to me it looks like this is accidentally overwriting the `==` method, so the include? check fails.

**Comment by twalpole** [comment]
@Aqualon  Thanks for that - investigating

**Comment by twalpole** [comment]
@Aqualon  What driver are you using?

**Comment by twalpole** [comment]
@Aqualon I think it looks like your inclusion of Capybara::Node::Matchers is somehow overriding the == method of nil, or Symbol ? --  Capybara::Node::Matchers is only for inclusion into  Capybara::Node::Base and Capybara::Node::Simple - so I think this is user error and you're going to have to figure out why you're including Capybara::Node::Matchers anywhere else.

**Comment by twalpole** [comment]
Confirmed - by including Capybara::Node::Matchers into global scope you've included it into the Object class 

irb(main):005:0> include Capybara::Node::Matchers
=> Object
irb(main):006:0> Object.ancestors
=> [Object, Capybara::Node::Matchers, Kernel, BasicObject]

which includes it into almost everything, including NilClass  --  You can't do that.
