### ISSUE TITLE
Weird issue in Webkit and Selenium

### ISSUE THREAD

**Issue by tmancino** [teamcapybara/capybara#801]
I was unable to get the Selenum default driver to work in a rails 3.2.3 app. In firefox it would quickly display an error message indicating that the CSS wasn't available. The following error is reported in the terminal:

Selenium::WebDriver::Error::ElementNotVisibleError:
       Element is not currently visible and so may not be interacted with
     # [remote server] file:///var/folders/vz/cgz719tn64n_jdmzj1tcm3w00000gp/T/webdriver-profile20120901-5039-  14dubxd/extensions/fxdriver@googlecode.com/components/command_processor.js:5908:in `unknown'

There is also an error, which flew by so fast I couldn't read it in the browser. Switching to the chrome driver, caused it to hang and the following error is reported in the browser window:

Error compiling CSS asset

NameError: undefined local variable or method 'app' for #
<ActiveSpport::Cache::FileStore: xxxx>

/rack/test/methods.rb:31 in 'build_rack_mock_session'

When I switch to webkit, I get several errors in the terminal like this: 

undefined|0|Error: NameError: undefined local variable or method `app' for #ActiveSupport::Cache::FileStore:0x007ff4ac78df18
http://127.0.0.1:53889/|115|SyntaxError: Parse error
undefined|0|ReferenceError: Can't find variable: $

but the test pass! 

Any idea where to look for the issue? Is it a rack-test thing? Thanks!
