### ISSUE TITLE
undefined method `readonly?' for Capybara::Node::Simple

### ISSUE THREAD

**Issue by mockdeep** [teamcapybara/capybara#2394]
## Meta

Version 3.33.0. It also fails on 2.18.0, but works on 2.7.1.

Driver Information (and browser if relevant): not relevant, we're writing view specs using `Capybara.string`

## Expected Behavior

Test finds field that is readonly.

## Actual Behavior

Test throws an error:

```
NoMethodError:
       undefined method `readonly?' for #<Capybara::Node::Simple:0x000000000cafbd90>
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/selector/definition/field.rb:24:in `block (2 levels) in <top (required)>'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/selector/filters/node_filter.rb:14:in `block in initialize'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/selector/filters/base.rb:59:in `instance_exec'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/selector/filters/base.rb:59:in `apply'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/selector/filters/node_filter.rb:24:in `matches?'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/queries/selector_query.rb:286:in `block (2 levels) in matches_node_filters?'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/queries/selector_query.rb:276:in `each'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/queries/selector_query.rb:276:in `all?'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/queries/selector_query.rb:276:in `block in matches_node_filters?'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/selector/selector.rb:85:in `with_filter_errors'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/queries/selector_query.rb:275:in `matches_node_filters?'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/queries/selector_query.rb:117:in `matches_filters?'
     # /home/fletch/.rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/result.rb:32:in `block in initialize'
     # /home/fletch/.rvm/gems/ruby-2.6.6/bin/rspec:1:in `each'
     # /home/fletch/.rvm/gems/ruby-2.6.6/bin/rspec:1:in `each'
     # /home/fletch/.rvm/gems/ruby-2.6.6/bin/rspec:1:in `each'
     # /home/fletch/.rvm/gems/ruby-2.6.6/bin/rspec:1:in `each'
```

## Steps to reproduce

```rb
html = <<~HTML
  <div>
    <input readonly="readonly" value="puff" type="text" name="approver_name" />
  </div>
HTML
expect(html).to have_field :approver_name, with: 'puff', readonly: true

# or

Capybara.string(html).find(:field, :approver_name, with: 'puff', readonly: true)
```

**Comment by twalpole** [comment]
Should be fixed in master branch
