### ISSUE TITLE
Puma 6.0.0 - Error calling ::Puma::Events.strings

### ISSUE THREAD

**Issue by lucasfais** [teamcapybara/capybara#2602]
Error after upgrading `puma` from 5.6.5 to 6.0.0.

## Meta
Capybara Version: 3.37.1

Driver Information (and browser if relevant): webdrivers (5.2.0), selenium-webdriver (4.5.0)

## Expected Behavior
Tests should work as before.

## Actual Behavior

This error is raised:
```
Failure/Error: events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio

NoMethodError:
  undefined method `strings' for Puma::Events:Class

    events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio
                                                   ^^^^^^^^
# /home/runner/work/Fishis-Fast/Fishis-Fast/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/registrations/servers.rb:32:in `block in <top (required)>'
# /home/runner/work/Fishis-Fast/Fishis-Fast/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/config.rb:64:in `block in server='
# /home/runner/work/Fishis-Fast/Fishis-Fast/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/server.rb:77:in `block in boot'
```

## Steps to reproduce

Upgrade `puma` to 6.0.0.

**Comment by lucasfais** [comment]
oh, that's great. Thank you!
