### ISSUE TITLE
undefined method `visit' using Capybara 2.1 with RSpec and Rails 3.2

### ISSUE THREAD

**Issue by alexch** [teamcapybara/capybara#1177]
In a freshly generated Rails 3.2.14 app, using Capybara 2.1.0 and RSpec 2.14.6, the "visit" method is not found inside an integration spec.

```
 Failure/Error: visit "/"
 NoMethodError:
   undefined method `visit' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_1:0x007f9fa3d7d8a0>
```

For detailed reproduction instructions, do Michael Hartl's tutorial, Rails 3.2, chapter 3 --  http://ruby.railstutorial.org/chapters/static-pages?version=3.2 -- but don't fix the capybara version number in the Gemfile.

Workaround: in spec_helper.rb, inside the RSpec::configure block, add 

   `include Capybara::DSL`

I'm reporting this to Capybara since this works with Capybara 1.1.2 and the same version of RSpec, but I haven't looked into the code to see where the fault lies... should I report it to https://github.com/rspec/rspec-rails as well?
