### ISSUE TITLE
Step Definitions in web_steps.rb not working in 0.4.0.rc

### ISSUE THREAD

**Issue by wjdix** [teamcapybara/capybara#156]
Specifically "When I follow ... within ..."
It gives error: undefined local variable or method `node' for #Capybara::Driver::RackTest::Node:0x109a1b968 (NameError)
I tried regenerating the web_steps file, and the problem persisted.
