### ISSUE TITLE
winthin_window is not working with capybara gem version 3.7.2

### ISSUE THREAD

**Issue by vidhijain24** [teamcapybara/capybara#2299]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:3.7.2
Driver Information (and browser if relevant):

## Expected Behavior
I should switch to new window

## Actual Behavior
Error: undefined method `ArgumentError for #

## Steps to reproduce

`old_window=page.driver.browser.window_handles.first`
 `begin`
 `        within_window (page.driver.browser.window_handles.last) do        `    
`               open_admin_from_portal`
`               page.current_window.close  `
`         end`
`         rescue Selenium::WebDriver::Error::NoSuchWindowError`
`         page.driver.browser.switch_to.window(old_window)`
`         com_wait_less`
 `end`

The above code was working when I was using capybara 2.7. Now I have upgrade my capybara version to 3.7.2. After upgrading within_window is not working anymore.

**Comment by twalpole** [comment]
@vidhijain24 Moving from 2.7 to 3.x is a major version bump so there are expected to be breaking changes.  Also, why are you moving to 3.7.x, that's very out of date since 3.31.x is the latest version. 
 Additionally you're calling `page.driver.xxx` methods which means you're making driver specific calls (which you shouldn't be doing) rather than using the Capybara window API.  Time to update your code.  I don't know exactly what you're trying to do with the code you show since order of window handles is not guaranteed so using `first` and `last` doesn't really tell me anything and you don't show how any of the windows are opened, but the methods in https://rubydoc.info/github/teamcapybara/capybara/master/Capybara/Window are what you should be using.

**Comment by vidhijain24** [comment]
@twalpole oh yeah, I also tried the latest version of capybara. After your guidance, I used window API to switch to the new window. But how I can handle the parent window and how I can switch it back to the parent window?

**Comment by twalpole** [comment]
@vidhijain24 How are you getting each of those?  You should only be dealing with Capybara::Window objects.

**Comment by vidhijain24** [comment]
@twalpole 

I am on window A. Window A has a link which opens a window B on new tab. Then window B has a button. When I clicked to button, it opens a pop up window C. I want to handle window A to B, then B to C.

1. #<Window @handle="CDwindow-DFC916D29EC814A257E570239695302F">
The above I am getting when I click to a link and it opens a new window tab B.

2.#Capybara::Window:0x00000007224cd0
The above I am getting when I am clicking on the button and it opens a popup window C.

Can I handle all three windows by window API?

**Comment by twalpole** [comment]
@vidhijain24 All windows are definitely handleable by the window API. Show your code

**Comment by vidhijain24** [comment]
@twalpole 
Below is my code:
`def self.contract_admin_cancellation data, example`
`        com_click_JS $DA_csr_ca_searched_contract_number, 'clicked on contract number', example`
`        old_window=page.driver.browser.window_handles.first`
`        begin`
`        within_window (page.driver.browser.window_handles.last) do`
`          com_click $DA_csr_ca_contract_admin_button, 'clicked on contract admin button', example`
`         page.current_window.close`
`        end`
`        rescue Selenium::WebDriver::Error::NoSuchWindowError`
`        end`
`        begin`
`        within_window (page.driver.browser.window_handles.last) do`
`           self.validate_contract_status 'Active', example`
`           self.click_cancellation_button example`
`           DA_CPQ_COMMUNITY.verify_contract_cancel_active_agreement_labels example`
`           self.set_cancellation_reason data, example`
`           page.current_window.close`
`         end`
`         rescue Selenium::WebDriver::Error::NoSuchWindowError`
`           page.driver.browser.switch_to.window(old_window)`
 `        end`
 `end`
![image](https://user-images.githubusercontent.com/60422141/73422552-5b368b00-434f-11ea-8a5f-e28304bff1da.png)

**Comment by twalpole** [comment]
Again, you really SHOULD NOT be using page.driver.xxx anywhere in your tests - That makes your code driver specific and also means you can't use the results of those methods with Capybaras API. Using Capybaras window API your code should look something like

```
admin_window = page.window_opened_by do
    # click the contract number here
end

popup_window = page.within_window(admin_window) do
    page.window_opened_by do
      # click the admin button here
    end
end
admin_window.close

page.within_window(popup_window) do
    # do whatever you want in the popup window
end
popup_window.close
```

**Comment by vidhijain24** [comment]
@twalpole It's awesome.. Thank you for your help.
