### ISSUE TITLE
url and path helpers do not work in 1.0.1

### ISSUE THREAD

**Issue by LegendSzymon-P** [teamcapybara/capybara#468]
After i've upgraded to capybara 1.0.1 from 1.0.0, i get undefined method error for any path/url helper in my capybara tests. I'm using capybara with steak. Here is a backtrace:

```
/home/apocalyptiq/apps/app/spec/acceptance/browse_products_spec.rb:97:in `block (2 levels) in <top (required)>': undefined local variable or method `root_path' for #<Class:0xa78c968> (NameError)
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:142:in `module_eval'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:142:in `subclass'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:129:in `describe'
from /home/apocalyptiq/apps/farmera/spec/acceptance/browse_products_spec.rb:86:in `block in <top (required)>'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:142:in `module_eval'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:142:in `subclass'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:129:in `describe'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/dsl.rb:5:in `describe'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/capybara-1.0.1/lib/capybara/rspec/features.rb:19:in `feature'
from /home/apocalyptiq/apps/app/spec/acceptance/browse_products_spec.rb:4:in `<top (required)>'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `load'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `block in load_spec_files'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `map'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `load_spec_files'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:18:in `run'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:80:in `run_in_process'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:69:in `run'
from /home/apocalyptiq/.rvm/gems/ruby-1.9.2-p180/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:11:in `block in autorun'
```

I have the same error when I run this test with bare capybara, without steak, so i think that it is a capybara bug.
